In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\ABDULMUIZ AKOREDE\Downloads\Breast Cancer METABRIC.csv")
df.head(3)

,Patient ID,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Cancer Type Detailed,Cellularity,Chemotherapy,Pam50 + Claudin-low subtype,Cohort,ER status measured by IHC,...,Overall Survival Status,PR Status,Radio Therapy,Relapse Free Status (Months),Relapse Free Status,Sex,3-Gene classifier subtype,Tumor Size,Tumor Stage,Patient's Vital Status
0,MB-0000,75.65,Mastectomy,Breast Cancer,Breast Invasive Ductal Carcinoma,NaN,No,claudin-low,1.0,Positve,...,Living,Negative,Yes,138.65,Not Recurred,Female,ER-/HER2-,22.0,2.0,Living
1,MB-0002,43.19,Breast Conserving,Breast Cancer,Breast Invasive Ductal Carcinoma,High,No,LumA,1.0,Positve,...,Living,Positive,Yes,83.52,Not Recurred,Female,ER+/HER2- High Prolif,10.0,1.0,Living
2,MB-0005,48.87,Mastectomy,Breast Cancer,Breast Invasive Ductal Carcinoma,High,Yes,LumB,1.0,Positve,...,Deceased,Positive,No,151.28,Recurred,Female,NaN,15.0,2.0,Died of Disease

In [3]:
pd.set_option('display.max.columns',34 )

In [4]:
df2=df[['Patient ID', 'Age at Diagnosis', 'Type of Breast Surgery', 'Cancer Type Detailed',
  'Chemotherapy', 'Hormone Therapy', 'Radio Therapy', 'Patient\'s Vital Status']]
df2

,Patient ID,Age at Diagnosis,Type of Breast Surgery,Cancer Type Detailed,Chemotherapy,Hormone Therapy,Radio Therapy,Patient's Vital Status
0,MB-0000,75.65,Mastectomy,Breast Invasive Ductal Carcinoma,No,Yes,Yes,Living
1,MB-0002,43.19,Breast Conserving,Breast Invasive Ductal Carcinoma,No,Yes,Yes,Living
2,MB-0005,48.87,Mastectomy,Breast Invasive Ductal Carcinoma,Yes,Yes,No,Died of Disease
3,MB-0006,47.68,Mastectomy,Breast Mixed Ductal and Lobular Carcinoma,Yes,Yes,Yes,Living
4,MB-0008,76.97,Mastectomy,Breast Mixed Ductal and Lobular Carcinoma,Yes,Yes,Yes,Died of Disease
...,...,...,...,...,...,...,...,...
2504,MTS-T2428,70.05,NaN,Invasive Breast Carcinoma,NaN,NaN,NaN,NaN
2505,MTS-T2429,63.60,NaN,Invasive Breast Carcinoma,NaN,NaN,NaN,NaN
2506,MTS-T2430,NaN,NaN,Invasive Breast Carcinoma,NaN,NaN,NaN,NaN
2507,MTS-T2431,NaN,NaN,Invasive Breast Carcinoma,NaN,NaN,NaN,NaN
2508,MTS-T2432,NaN,NaN,Invasive Breast Carcinoma,NaN,NaN,NaN,NaN

In [5]:
df2.head(7)

,Patient ID,Age at Diagnosis,Type of Breast Surgery,Cancer Type Detailed,Chemotherapy,Hormone Therapy,Radio Therapy,Patient's Vital Status
0,MB-0000,75.65,Mastectomy,Breast Invasive Ductal Carcinoma,No,Yes,Yes,Living
1,MB-0002,43.19,Breast Conserving,Breast Invasive Ductal Carcinoma,No,Yes,Yes,Living
2,MB-0005,48.87,Mastectomy,Breast Invasive Ductal Carcinoma,Yes,Yes,No,Died of Disease
3,MB-0006,47.68,Mastectomy,Breast Mixed Ductal and Lobular Carcinoma,Yes,Yes,Yes,Living
4,MB-0008,76.97,Mastectomy,Breast Mixed Ductal and Lobular Carcinoma,Yes,Yes,Yes,Died of Disease
5,MB-0010,78.77,Mastectomy,Breast Invasive Ductal Carcinoma,No,Yes,Yes,Died of Disease
6,MB-0014,56.45,Breast Conserving,Breast Invasive Ductal Carcinoma,Yes,Yes,Yes,Living

In [6]:
df['Chemotherapy'].value_counts()

Chemotherapy
No     1568
Yes     412
Name: count, dtype: int64

In [7]:
df['Hormone Therapy'].value_counts()

Hormone Therapy
Yes    1216
No      764
Name: count, dtype: int64

In [8]:
df['Radio Therapy'].value_counts()

Radio Therapy
Yes    1173
No      807
Name: count, dtype: int64

In [20]:
df5=df[['Chemotherapy', 'Hormone Therapy', 'Radio Therapy']].value_counts().to_frame()
df5.to_csv(r"C:\Users\ABDULMUIZ AKOREDE\Documents\Project.py\New_data_file\three_files.csv")

In [9]:
pd.crosstab(index=df['Patient\'s Vital Status'],
           columns='counts')

col_0                   counts
Patient's Vital Status
Died of Disease            646
Died of Other Causes       497
Living                     837

In [10]:
df3=pd.crosstab(index=df['Patient\'s Vital Status'],
           columns=[df['Hormone Therapy'],
                    df['Chemotherapy'],
                    df['Radio Therapy']],
            margins=True
                    )
df3

Hormone Therapy          No                Yes                 All
Chemotherapy             No      Yes        No      Yes
Radio Therapy            No  Yes  No  Yes   No  Yes  No  Yes
Patient's Vital Status
Died of Disease          85   53  29   90  125  183  17   64   646
Died of Other Causes    104   55   2    7  150  164   2   12   496
Living                  122  123  17   76  144  259  10   86   837
All                     311  231  48  173  419  606  29  162  1979

In [11]:
df3.to_csv(r"C:\Users\ABDULMUIZ AKOREDE\Documents\Project.py\New_data_file\Homo_chemo_rad.csv")

In [12]:
pd.crosstab(index=df['Relapse Free Status'],
            columns='Counts')

col_0                Counts
Relapse Free Status
Not Recurred           1486
Recurred               1002

In [13]:
df4=pd.crosstab(index=df['Relapse Free Status'],
           columns=[df['Hormone Therapy'],
                    df['Chemotherapy'],
                    df['Radio Therapy']],
            margins=True
                    )
df4

Hormone Therapy       No                Yes                 All
Chemotherapy          No      Yes        No      Yes
Radio Therapy         No  Yes  No  Yes   No  Yes  No  Yes
Relapse Free Status
Not Recurred         194  154  18   79  265  373   9   84  1176
Recurred             117   77  30   94  154  233  20   78   803
All                  311  231  48  173  419  606  29  162  1979

In [25]:
df4=pd.crosstab(index=[df['Relapse Free Status'],
                      df['Overall Survival Status'],
                      df['Patient\'s Vital Status']],
           columns=[df['Hormone Therapy'],
                    df['Chemotherapy'],
                    df['Radio Therapy']],
                
                    )
df4.to_csv(r"C:\Users\ABDULMUIZ AKOREDE\Documents\Project.py\New_data_file\crosstab.csv")

In [24]:
df5=df[['Chemotherapy', 'Hormone Therapy', 'Radio Therapy', 'Patient\'s Vital Status']].value_counts().to_frame()
df5

                                                                   count
Chemotherapy Hormone Therapy Radio Therapy Patient's Vital Status
No           Yes             Yes           Living                    259
                                           Died of Disease           183
                                           Died of Other Causes      164
                             No            Died of Other Causes      150
                                           Living                    144
                                           Died of Disease           125
             No              Yes           Living                    123
                             No            Living                    122
                                           Died of Other Causes      104
Yes          No              Yes           Died of Disease            90
             Yes             Yes           Living                     86
No           No              No            Died of Disease            85
Yes          No              Yes           Living                     76
             Yes             Yes           Died of Disease            64
No           No              Yes           Died of Other Causes       55
                                           Died of Disease            53
Yes          No              No            Died of Disease            29
                                           Living                     17
             Yes             No            Died of Disease            17
                             Yes           Died of Other Causes       12
                             No            Living                     10
             No              Yes           Died of Other Causes        7
                             No            Died of Other Causes        2
             Yes             No            Died of Other Causes        2