In [3]:
import pandas as pd

In [9]:
df=pd.read_excel(r"C:\Users\ABDULMUIZ AKOREDE\Documents\Project.py\Website scraping prj\Hockey.xlsx")

In [10]:
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,NaN,0.550,299,264,35
1,Buffalo Sabres,1990,31,30,NaN,0.388,292,278,14
2,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,NaN,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,NaN,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,NaN,0.463,272,272,0
6,Hartford Whalers,1990,31,38,NaN,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,NaN,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,NaN,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,NaN,0.487,273,249,24
10,New Jersey Devils,1990,32,33,NaN,0.400,272,264,8
11,New York Islanders,1990,25,45,NaN,0.312,223,290,-67
12,New York Rangers,1990,36,31,NaN,0.450,297,265,32
13,Philadelphia Flyers,1990,33,37,NaN,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,NaN,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,NaN,0.200,236,354,-118
16,St. Louis Blues,1990,47,22,NaN,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,NaN,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,NaN,0.350,243,315,-72
19,Washington Capitals,1990,37,36,NaN,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,NaN,0.325,260,288,-28
21,Boston Bruins,1991,36,32,NaN,0.450,270,275,-5
22,Buffalo Sabres,1991,31,37,NaN,0.388,289,299,-10
23,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,NaN,0.450,257,236,21
25,Boston Bruins,1990,44,24,NaN,0.550,299,264,35
26,Buffalo Sabres,1990,31,30,NaN,0.388,292,278,14
27,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
28,Chicago Blackhawks,1990,49,23,NaN,0.613,284,211,73
29,Detroit Red Wings,1990,34,38,NaN,0.425,273,298,-25
30,Edmonton Oilers,1990,37,37,NaN,0.463,272,272,0
31,Hartford Whalers,1990,31,38,NaN,0.388,238,276,-38
32,Los Angeles Kings,1990,46,24,NaN,0.575,340,254,86
33,Minnesota North Stars,1990,27,39,NaN,0.338,256,266,-10
34,Montreal Canadiens,1990,39,30,NaN,0.487,273,249,24
35,New Jersey Devils,1990,32,33,NaN,0.400,272,264,8
36,New York Islanders,1990,25,45,NaN,0.312,223,290,-67
37,New York Rangers,1990,36,31,NaN,0.450,297,265,32
38,Philadelphia Flyers,1990,33,37,NaN,0.412,252,267,-15
39,Pittsburgh Penguins,1990,41,33,NaN,0.512,342,305,37
40,Quebec Nordiques,1990,16,50,NaN,0.200,236,354,-118
41,St. Louis Blues,1990,47,22,NaN,0.588,310,250,60
42,Toronto Maple Leafs,1990,23,46,NaN,0.287,241,318,-77
43,Vancouver Canucks,1990,28,43,NaN,0.350,243,315,-72
44,Washington Capitals,1990,37,36,NaN,0.463,258,258,0
45,Winnipeg Jets,1990,26,43,NaN,0.325,260,288,-28
46,Boston Bruins,1991,36,32,NaN,0.450,270,275,-5
47,Buffalo Sabres,1991,31,37,NaN,0.388,289,299,-10
48,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9
49,Chicago Blackhawks,1991,36,29,NaN,0.450,257,236,21

In [18]:
df.tail()

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
45,Winnipeg Jets,1990,26,43,NaN,0.325,260,288,-28
46,Boston Bruins,1991,36,32,NaN,0.450,270,275,-5
47,Buffalo Sabres,1991,31,37,NaN,0.388,289,299,-10
48,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9
49,Chicago Blackhawks,1991,36,29,NaN,0.450,257,236,21

In [17]:
df[df['Wins']<=20]

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
15,Quebec Nordiques,1990,16,50,NaN,0.2,236,354,-118
40,Quebec Nordiques,1990,16,50,NaN,0.2,236,354,-118

In [19]:
team_name=['Buffalo Sabres', 'Calgary Flames']
df[df['Team Name'].isin(team_name)]

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
1,Buffalo Sabres,1990,31,30,NaN,0.388,292,278,14
2,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
22,Buffalo Sabres,1991,31,37,NaN,0.388,289,299,-10
23,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9
26,Buffalo Sabres,1990,31,30,NaN,0.388,292,278,14
27,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
47,Buffalo Sabres,1991,31,37,NaN,0.388,289,299,-10
48,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9

In [20]:
df[df['Team Name'].str.contains('Calgary Flames')]

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
2,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
23,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9
27,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
48,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9

In [22]:
df2=df.set_index('Year')
df2

,Team Name,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
Year,,,,,,,,
1990,Boston Bruins,44,24,NaN,0.550,299,264,35
1990,Buffalo Sabres,31,30,NaN,0.388,292,278,14
1990,Calgary Flames,46,26,NaN,0.575,344,263,81
1990,Chicago Blackhawks,49,23,NaN,0.613,284,211,73
1990,Detroit Red Wings,34,38,NaN,0.425,273,298,-25
1990,Edmonton Oilers,37,37,NaN,0.463,272,272,0
1990,Hartford Whalers,31,38,NaN,0.388,238,276,-38
1990,Los Angeles Kings,46,24,NaN,0.575,340,254,86
1990,Minnesota North Stars,27,39,NaN,0.338,256,266,-10
1990,Montreal Canadiens,39,30,NaN,0.487,273,249,24
1990,New Jersey Devils,32,33,NaN,0.400,272,264,8
1990,New York Islanders,25,45,NaN,0.312,223,290,-67
1990,New York Rangers,36,31,NaN,0.450,297,265,32
1990,Philadelphia Flyers,33,37,NaN,0.412,252,267,-15
1990,Pittsburgh Penguins,41,33,NaN,0.512,342,305,37
1990,Quebec Nordiques,16,50,NaN,0.200,236,354,-118
1990,St. Louis Blues,47,22,NaN,0.588,310,250,60
1990,Toronto Maple Leafs,23,46,NaN,0.287,241,318,-77
1990,Vancouver Canucks,28,43,NaN,0.350,243,315,-72
1990,Washington Capitals,37,36,NaN,0.463,258,258,0
1990,Winnipeg Jets,26,43,NaN,0.325,260,288,-28
1991,Boston Bruins,36,32,NaN,0.450,270,275,-5
1991,Buffalo Sabres,31,37,NaN,0.388,289,299,-10
1991,Calgary Flames,31,37,NaN,0.388,296,305,-9
1991,Chicago Blackhawks,36,29,NaN,0.450,257,236,21
1990,Boston Bruins,44,24,NaN,0.550,299,264,35
1990,Buffalo Sabres,31,30,NaN,0.388,292,278,14
1990,Calgary Flames,46,26,NaN,0.575,344,263,81
1990,Chicago Blackhawks,49,23,NaN,0.613,284,211,73
1990,Detroit Red Wings,34,38,NaN,0.425,273,298,-25
1990,Edmonton Oilers,37,37,NaN,0.463,272,272,0
1990,Hartford Whalers,31,38,NaN,0.388,238,276,-38
1990,Los Angeles Kings,46,24,NaN,0.575,340,254,86
1990,Minnesota North Stars,27,39,NaN,0.338,256,266,-10
1990,Montreal Canadiens,39,30,NaN,0.487,273,249,24
1990,New Jersey Devils,32,33,NaN,0.400,272,264,8
1990,New York Islanders,25,45,NaN,0.312,223,290,-67
1990,New York Rangers,36,31,NaN,0.450,297,265,32
1990,Philadelphia Flyers,33,37,NaN,0.412,252,267,-15
1990,Pittsburgh Penguins,41,33,NaN,0.512,342,305,37
1990,Quebec Nordiques,16,50,NaN,0.200,236,354,-118
1990,St. Louis Blues,47,22,NaN,0.588,310,250,60
1990,Toronto Maple Leafs,23,46,NaN,0.287,241,318,-77
1990,Vancouver Canucks,28,43,NaN,0.350,243,315,-72
1990,Washington Capitals,37,36,NaN,0.463,258,258,0
1990,Winnipeg Jets,26,43,NaN,0.325,260,288,-28
1991,Boston Bruins,36,32,NaN,0.450,270,275,-5
1991,Buffalo Sabres,31,37,NaN,0.388,289,299,-10
1991,Calgary Flames,31,37,NaN,0.388,296,305,-9
1991,Chicago Blackhawks,36,29,NaN,0.450,257,236,21

In [41]:
df3=df2.filter(items=['Team Name', 'Wins', 'Losses', '+ / -'])
df3

                  Team Name  Wins  Losses  + / -
Year
1990          Boston Bruins    44      24     35
1990         Buffalo Sabres    31      30     14
1990         Calgary Flames    46      26     81
1990     Chicago Blackhawks    49      23     73
1990      Detroit Red Wings    34      38    -25
1990        Edmonton Oilers    37      37      0
1990       Hartford Whalers    31      38    -38
1990      Los Angeles Kings    46      24     86
1990  Minnesota North Stars    27      39    -10
1990     Montreal Canadiens    39      30     24
1990      New Jersey Devils    32      33      8
1990     New York Islanders    25      45    -67
1990       New York Rangers    36      31     32
1990    Philadelphia Flyers    33      37    -15
1990    Pittsburgh Penguins    41      33     37
1990       Quebec Nordiques    16      50   -118
1990        St. Louis Blues    47      22     60
1990    Toronto Maple Leafs    23      46    -77
1990      Vancouver Canucks    28      43    -72
1990    Washington Capitals    37      36      0
1990          Winnipeg Jets    26      43    -28
1991          Boston Bruins    36      32     -5
1991         Buffalo Sabres    31      37    -10
1991         Calgary Flames    31      37     -9
1991     Chicago Blackhawks    36      29     21
1990          Boston Bruins    44      24     35
1990         Buffalo Sabres    31      30     14
1990         Calgary Flames    46      26     81
1990     Chicago Blackhawks    49      23     73
1990      Detroit Red Wings    34      38    -25
1990        Edmonton Oilers    37      37      0
1990       Hartford Whalers    31      38    -38
1990      Los Angeles Kings    46      24     86
1990  Minnesota North Stars    27      39    -10
1990     Montreal Canadiens    39      30     24
1990      New Jersey Devils    32      33      8
1990     New York Islanders    25      45    -67
1990       New York Rangers    36      31     32
1990    Philadelphia Flyers    33      37    -15
1990    Pittsburgh Penguins    41      33     37
1990       Quebec Nordiques    16      50   -118
1990        St. Louis Blues    47      22     60
1990    Toronto Maple Leafs    23      46    -77
1990      Vancouver Canucks    28      43    -72
1990    Washington Capitals    37      36      0
1990          Winnipeg Jets    26      43    -28
1991          Boston Bruins    36      32     -5
1991         Buffalo Sabres    31      37    -10
1991         Calgary Flames    31      37     -9
1991     Chicago Blackhawks    36      29     21

In [42]:
team_nad=['Montreal Canadiens', 'Calgary Flames']
df3[df3['Team Name'].isin(team_nad)]

               Team Name  Wins  Losses  + / -
Year
1990      Calgary Flames    46      26     81
1990  Montreal Canadiens    39      30     24
1991      Calgary Flames    31      37     -9
1990      Calgary Flames    46      26     81
1990  Montreal Canadiens    39      30     24
1991      Calgary Flames    31      37     -9

In [43]:
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,NaN,0.550,299,264,35
1,Buffalo Sabres,1990,31,30,NaN,0.388,292,278,14
2,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,NaN,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,NaN,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,NaN,0.463,272,272,0
6,Hartford Whalers,1990,31,38,NaN,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,NaN,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,NaN,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,NaN,0.487,273,249,24
10,New Jersey Devils,1990,32,33,NaN,0.400,272,264,8
11,New York Islanders,1990,25,45,NaN,0.312,223,290,-67
12,New York Rangers,1990,36,31,NaN,0.450,297,265,32
13,Philadelphia Flyers,1990,33,37,NaN,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,NaN,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,NaN,0.200,236,354,-118
16,St. Louis Blues,1990,47,22,NaN,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,NaN,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,NaN,0.350,243,315,-72
19,Washington Capitals,1990,37,36,NaN,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,NaN,0.325,260,288,-28
21,Boston Bruins,1991,36,32,NaN,0.450,270,275,-5
22,Buffalo Sabres,1991,31,37,NaN,0.388,289,299,-10
23,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,NaN,0.450,257,236,21
25,Boston Bruins,1990,44,24,NaN,0.550,299,264,35
26,Buffalo Sabres,1990,31,30,NaN,0.388,292,278,14
27,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
28,Chicago Blackhawks,1990,49,23,NaN,0.613,284,211,73
29,Detroit Red Wings,1990,34,38,NaN,0.425,273,298,-25
30,Edmonton Oilers,1990,37,37,NaN,0.463,272,272,0
31,Hartford Whalers,1990,31,38,NaN,0.388,238,276,-38
32,Los Angeles Kings,1990,46,24,NaN,0.575,340,254,86
33,Minnesota North Stars,1990,27,39,NaN,0.338,256,266,-10
34,Montreal Canadiens,1990,39,30,NaN,0.487,273,249,24
35,New Jersey Devils,1990,32,33,NaN,0.400,272,264,8
36,New York Islanders,1990,25,45,NaN,0.312,223,290,-67
37,New York Rangers,1990,36,31,NaN,0.450,297,265,32
38,Philadelphia Flyers,1990,33,37,NaN,0.412,252,267,-15
39,Pittsburgh Penguins,1990,41,33,NaN,0.512,342,305,37
40,Quebec Nordiques,1990,16,50,NaN,0.200,236,354,-118
41,St. Louis Blues,1990,47,22,NaN,0.588,310,250,60
42,Toronto Maple Leafs,1990,23,46,NaN,0.287,241,318,-77
43,Vancouver Canucks,1990,28,43,NaN,0.350,243,315,-72
44,Washington Capitals,1990,37,36,NaN,0.463,258,258,0
45,Winnipeg Jets,1990,26,43,NaN,0.325,260,288,-28
46,Boston Bruins,1991,36,32,NaN,0.450,270,275,-5
47,Buffalo Sabres,1991,31,37,NaN,0.388,289,299,-10
48,Calgary Flames,1991,31,37,NaN,0.388,296,305,-9
49,Chicago Blackhawks,1991,36,29,NaN,0.450,257,236,21

In [52]:
df3[df3['Wins']>=47].sort_values(by='Wins', ascending=True)

               Team Name  Wins  Losses  + / -
Year
1990     St. Louis Blues    47      22     60
1990     St. Louis Blues    47      22     60
1990  Chicago Blackhawks    49      23     73
1990  Chicago Blackhawks    49      23     73